app/models.py
from mongoengine import StringField, IntField, Document, ListField, DictField, DateTimeField
from datetime import datetime


class Suburb():

    _instances = {}

    # id = IntField(required=True, primary_key=True)
    # name = StringField(required=True, max_length=50)
    # lga = StringField(required=True, max_length=50)
    # crime_stats = DictField(required=True)
    # acc_stats = ListField(required=True)
    # poi = ListField(required=True)
    # poi_rate = DictField(required=True)
    # wiki = StringField(required=True)
    # rates = DictField(required=True)
    # last_updated = DateTimeField(required=True)

    def __init__(self, name, crime_stats, acc_stats, poi, wiki, *args, **kwargs):
        # Test
        super().__init__(*args, **kwargs)
        # self.id = len(self._instances)
        self.name = name
        self.crime_stats = crime_stats
        self.acc_stats = acc_stats
        self.poi = poi[0]
        self.poi_rate = poi[1]
        self.wiki = wiki[0]
        self.images = wiki[1]
        self._instances[name] = self
        self.rates = {}
        self.lga = None
        self.is_lga = False
        self.last_updated = datetime.now()
        self.acc_path = None
        self.poi_path = None
        self.rates_value = {}
        self.poi_locations = []
        self.poi_urls = []
        self.nb_of_pois = 0

    @classmethod
    def get_instance(cls, suburb_name):
        try:
            return cls._instances[suburb_name]
        except KeyError:
            return {}

    @classmethod
    def imported(cls, suburb_name):
        return suburb_name in cls._instances.keys()

    def set_rates(self, crime_rate, acc_rate, poi_rate, all_rate):
        self.rates = {'all': all_rate,
                      'crime': crime_rate,
                      'acc': acc_rate,
                      'poi': poi_rate}
        for key, value in self.rates.items():
            self.rates_value[key] = f'{float(value) / 20.0 : .1f}'

    def set_lga(self, lga):
        self.lga = lga
        self.is_lga = \
            self.lga == self.name

    def set_figure_paths(self, acc_path, poi_path):
        self.acc_path = acc_path
        self.poi_path = poi_path

    def set_poi_locations(self, poi_locations):
        self.poi_locations = poi_locations
        for poi in poi_locations:
            tmp = ','.join([str(poi['lat']), str(poi['lng'])])
            self.poi_urls.append(tmp)
        self.nb_of_pois = len(poi_locations)

app/views.py
'''

Author: @TC
Flask Application User Interface

'''
import os

from flask import request, render_template, Flask, redirect, url_for, send_from_directory
from flask import Blueprint
from flask_restful import reqparse
# from app.glue import routes as glue_routes
from app.models import Suburb
import app.glue as glue
import json
# import flask_restful
root = os.getcwd()
bp = Blueprint('app', __name__, url_prefix='', static_folder='/templates/')
# app = Flask(__name__)
# app.register_blueprint(bp)

# bp.add_url_rule(glue_routes['rule'],
#                 endpoint=glue_routes['endpoint'],
#                 view_func=glue_routes['view_func'],
#                 **glue_routes['options'])
GOOGLE_MAP_API_KEY = 'AIzaSyDbdgCBSoXfep6LvrUsPRciIDc6ov9KceA'


@bp.route('/', methods=['GET'])
def index():

    return render_template('app/index.html')


@bp.route('/suburb/<suburb_name>', methods=['GET'])
def show_results(suburb_name):
    '''
    render result html page
    :param suburb_name: a Suburb object containing all the information
    :return:
    '''
    if not Suburb.imported(suburb_name):
        return redirect(url_for('.index'))
    suburb = Suburb.get_instance(suburb_name)
    data = json.dumps(suburb.poi_locations)
    # occ = data.count('"')
    # data = data.replace(count=occ)
    return render_template('app/result.html', suburb=suburb, locations=data)


@bp.route('/search', methods=['POST'])
def search():
    # parser = re.RequestParser()
    # parser.add_argument('rt', type=str)
    # args = parser.parse_args()

    # postcode = re.form.get("postcode")
    suburb_name = request.form.get('suburb')
    suburb_name = suburb_name.replace('+', ' ')
    if Suburb.imported(suburb_name):
        return redirect(url_for('.show_results', suburb_name=suburb_name))
    if not glue.check_input(suburb_name):
        # correction = glue.correct_input(suburb_name)
        return redirect(url_for('.suburb_not_found', origin=suburb_name))

    suburb_obj = glue.get_suburb_obj(suburb_name)

    return redirect(url_for('.show_results', suburb_name=suburb_name))


@bp.route('/error', methods=['GET'])
def suburb_not_found():
    parser = reqparse.RequestParser()
    parser.add_argument('origin')
    # parser.add_argument('correction')
    args = parser.parse_args()

    origin = args.get('origin')
    # correction = args.get('correction')
    correction = glue.correct_input(origin)

    return render_template('app/suburb_not_found.html', origin=origin, correction=correction)


@bp.route('/figures/<path:filename>', methods=['GET'])
def send_figure(filename):
    path = root + '/templates/static/figures'
    return send_from_directory(path, filename)

templates/app/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %} - Error Page</title>
    <meta charset="'UTF-8">
</head>
<body>
    {% block body %} {% endblock %}
</body>
</html>

templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="'UTF-8">
    <!-- Bootstrap Stylesheet-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Rookie's Homepage</title>
    <style>
        .col-center-block {
            float: none;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
</head>
<body>

<div class="col-md-8 col-center-block">
    <h1 class="text-center">Suburb Information Search System</h1>
</div>
<div class="col-md-5 col-center-block input-group" style="margin-top: 120px; position: relative">
    <form method="post" action="{{url_for('app.search')}}">
        <table>
            <tr>
                <td><h2 class="col-center-block">Search suburb here</h2></td>
            </tr>
            <tr style="margin-top: 24px">
                <td><input type="text" name="suburb" class="form-control" placeholder="Example: Kingsford"></td>
                <td><input type="submit" value="submit" style="margin-left: 12px"/></td>
            </tr>
        </table>
    </form>
</div>
</body>
</html>

templates/app/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="'UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- Bootstrap Stylesheet-->
    <!--<link rel="stylesheet" href="css/bootstrap.css">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Suburb Information</title>
    <!--<style>-->
        <!--.col-center-block {-->
            <!--float: none;-->
            <!--display: block;-->
            <!--margin-left: auto;-->
            <!--margin-right: auto;-->
        <!--}-->
    <!--</style>-->
{#    <style>#}
{#       @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,600,700);#}
{#body { margin: 50px; text-align: center; font-family: 'Open Sans', sans-serif; background: #f2fbff; }#}
{#em { font-style: italic; }#}
{#h1 { font-size: 24px; margin-bottom: 25px; font-weight: bold; text-transform: uppercase; }#}
{#h2 { font-size: 16px; margin-bottom: 15px;}#}
{#    </style>#}
    <style>
        .star-ratings-sprite {
            background: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/2605/star-rating-sprite.png") repeat-x;
            font-size: 0;
            height: 21px;
            line-height: 0;
            overflow: hidden;
            text-indent: -999em;
            width: 110px;
            margin: 0 auto;
        }

        .star-ratings-sprite-rating {
          background: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/2605/star-rating-sprite.png") repeat-x;
          background-position: 0 100%;
          float: left;
          height: 21px;
          display: block;
        }
        /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
        #map {
            height: 100%;
        }
        /* Optional: Makes the sample page fill the window. */
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

    </style>
</head>
<body>

<div class="container">
    <h1>Suburb Information</h1>
    <p>Switch different tabs to see contents</p>
    <div>
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#overview" aria-controls="overview" aria-selected="true">Overview</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#crime" aria-controls="crime" aria-selected="false">Crime</a></li>
            <li>
                <a class="nav-link" data-toggle="tab" href="#acc" aria-controls="crime" aria-selected="false">Accommodation</a>
            </li>
            <li>
                <a class="nav-link" data-toggle="tab" href="#poi" aria-controls="poi" aria-selected="false">POI</a>
            </li>
        </ul>
    </div>
    <div class="tab-content" id="myTabContent">
        <div id="overview" class="tab-pane fade show active" aria-labelledby="home-tab">
            <h3 class="col-center-block">Overview</h3>
            <h4>{{suburb.name}} Summary</h4>
            <div class="form-group">
                <table>
                    <tr>
                        <td><h5>Summary</h5></td>
                        <td><div class="star-ratings-sprite"><span style="width: {{ suburb.rates['all'] }}%" class="star-ratings-sprite-rating"></span></div></td>
                        <td>({{ suburb.rates_value['all'] }} / 5.0 )</td>
                    </tr>
                    <tr>
                        <td><h5>Safety</h5></td>
                        <td><div class="star-ratings-sprite"><span style="width: {{ suburb.rates['crime'] }}%" class="star-ratings-sprite-rating"></span></div></td>
                        <td>({{ suburb.rates_value['crime'] }} / 5.0 )</td>
                    </tr>
                    <tr>
                        <td><h5>Rental</h5></td>
                        <td><div class="star-ratings-sprite"><span style="width: {{ suburb.rates['acc'] }}%" class="star-ratings-sprite-rating"></span></div></td>
                        <td>({{ suburb.rates_value['acc'] }} / 5.0 )</td>
                    </tr>
                    <tr>
                        <td><h5>Life Style</h5></td>
                        <td><div class="star-ratings-sprite"><span style="width:{{ suburb.rates['poi'] }}%" class="star-ratings-sprite-rating"></span></div></td>
                        <td>({{ suburb.rates_value['poi'] }} / 5.0 )</td>
                    </tr>
                </table>
            </div>
            <div>
                <p>Photo Section</p>
                {% for img in suburb.images[:3] %}
                <img src="{{ img }}" class="img-fluid" alt="Responsive image" style="width: 50%">
                {% endfor %}
            </div>
            <!--<p>From Wikipedia</p>-->
            <!--<p>{{suburb.wiki}}.</p>-->
            <div class="card">
                <div class="card-title">From Wikipedia</div>
                <div class="card-body" >
                    {% for wiki in suburb.wiki %}
                    {% if wiki.startswith('==') %}
                    <p><h5>{{ wiki }}</h5></p>
                    {% else %}
                    <p style="word-wrap: break-word">{{ wiki }}</p>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div>
                <!--<p>Weather Section (from WeatherWidget.io) (Only static)</p>-->
                <!--<div>-->
                    <!--<a class="weatherwidget-io" href="https://forecast7.com/en/n33d92151d23/kingsford/" data-label_1="KINGSFORD" data-label_2="WEATHER" data-theme="original" >KINGSFORD WEATHER</a>-->
                        <!--<script>-->
                        <!--!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');-->
                        <!--</script>-->
                <!--</div>-->
                <p>Weather Section (from accuweather.io) (location-based)</p>
                <div id="weather">
                    <a href="https://www.accuweather.com/en/au/kingsford/3496607/current-weather/3496607" class="aw-widget-legal">
                    <!--
                    By accessing and/or using this code snippet, you agree to AccuWeather’s terms and conditions (in English) which can be found at https://www.accuweather.com/en/free-weather-widgets/terms and AccuWeather’s Privacy Statement (in English) which can be found at https://www.accuweather.com/en/privacy.
                    -->
                    </a><div id="awtd1526997793562" class="aw-widget-36hour"  data-locationkey="22889" data-unit="f" data-language="en-us" data-useip="true" data-uid="awtd1526997793562" data-editlocation="true"></div><script type="text/javascript" src="https://oap.accuweather.com/launch.js"></script>
                </div>
            </div>
            <!--<p>Crime stats goes here...</p>-->
        </div>

        <div id="crime" class="tab-pane fade" aria-labelledby="crime-tab">
            <h3 class="col-center-block">Crime</h3>
{#            <p>Crime details goes here...</p>#}
            {% if not suburb.is_lga %}
                <p>{{ suburb.name }} is under {{ suburb.lga }} council...</p>
                <p>Showing data from {{ suburb.lga }}...</p>
            {% endif %}
{#            <p>{{suburb.crime_stats}}</p>#}
            <h4>Summary</h4>
            <p>The most frequent crime in this area is <b>{{ suburb.crime_stats['crime_type'] }}</b></p>
            <h4>Trend (be careful of the rising crimes in this area)</h4>
            {% if suburb.crime_stats['trend_24month_crime_type'] %}
            <p>In the last 2 years, <b>{{ suburb.crime_stats['trend_24month_crime_type'] }}</b> is increasing most rapidly.</p>
            {% else %}
            <p>Sorry, no related data found from the source for the last 2 years trend.</p>
            {% endif %}
            {% if suburb.crime_stats['trend_60month_crime_type'] %}
            <p>In the last 5 years, <b>{{ suburb.crime_stats['trend_60month_crime_type'] }}</b> is increasing most rapidly.</p>
            {% else %}
            <p>Sorry, no related data found from the source for the last 5 years trend.</p>
            {% endif %}
        </div>

        <div id="acc" class="tab-pane fade" aria-labelledby="acc-tab">
            <h3 class="col-center-block">Accommodation</h3>
{#            <p>Accommodation details goes here...</p>#}
            {% if suburb.is_lga %}
                <p>Showing data from {{ suburb.lga }}</p>
            {% endif %}
            <img src="{{ url_for('app.send_figure', filename = suburb.acc_path) }}" class="img-fluid" alt="Responsive image" style="width: 50%; align-content: center">
            <table>
                <tr>
                    <td><b>Type</b></td>
                    <td><b>Average Rental</b></td>
                </tr>
                {% for e in suburb.acc_stats %}
                <tr>
                    <td>{{ e['type'] }}</td>
                    <td>{{ e['average'] }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>

        <div id="poi" class="tab-pane fade" aria-labelledby="poi-tab">
            <h3 class="col-center-block">Places of Interests (POIs)</h3>
{#            <p>POI details goes here...</p>#}
{#            <p>{{suburb.poi}}</p>#}
{#            <p>Here's a button linked to Google Map</p>#}
            <div id="map"></div>
            <img src="{{ url_for('app.send_figure', filename = suburb.poi_path) }}" class="img-fluid" alt="Responsive image" style="width: 50%; align-content: center">
            <table>
                <tr>
                    <td><b>POI Name</b></td>
                    <td><b>POI Type</b></td>
                    <td><b>Google Map Link</b></td>
                </tr>
                {% for i in range(suburb.nb_of_pois) %}
                    <tr>
                        <td>{{ suburb.poi[i]['name'] }} </td>
                        <td><i>{{ suburb.poi[i]['type'] }}</i></td>
                        <td><a href="https://www.google.com.au/maps/search/{{ suburb.poi_urls[i] }}">{{ suburb.poi_locations[i] }}</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

<!-- Google Map JavaScript -->
<script>

      function initMap() {

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 3,
          center: {lat: -28.024, lng: 140.887}
        });

        // Create an array of alphabetical characters used to label the markers.
        var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

        // Add some markers to the map.
        // Note: The code uses the JavaScript Array.prototype.map() method to
        // create an array of markers based on a given "locations" array.
        // The map() method here has nothing to do with the Google Maps API.
        var markers = locations.map(function(location, i) {
          return new google.maps.Marker({
            position: location,
            label: labels[i % labels.length]
          });
        });

        // Add a marker clusterer to manage the markers.
        var markerCluster = new MarkerClusterer(map, markers,
            {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});
      }
      var locations = {{ suburb.poi_locations | tojson}}
    {#console.log({{ locations | safe }})#}
    {#console.log({{ suburb.poi_locations | tojson }})#}
    </script>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDbdgCBSoXfep6LvrUsPRciIDc6ov9KceA&callback=initMap">
    </script>

<!-- Optional JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/app/suburb_not_found.html
{% extends '/app/error.html' %}
{% block title %} Suburb Not Found {% endblock %}
{% block body %}
<body>
    <h1>Suburb Not Found</h1>
    <p>Seems <b>{{origin}}</b> is not a good input.</p>
    <p>Maybe you are looking for <b>{{correction}}</b>. Click the button below to search again.</p>
    <form method="post" action="{{ url_for('app.search') }}">
        <tr>
            <td><input type="text" name="suburb" class="form-control" value="{{correction}}"></td>
            <td><input type="submit" value="submit" style="margin-left: 12px"></td>
        </tr>
    </form>
</body>
{% endblock %}